version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Replace with your desired Java version
  pre_build:
    commands:
      - echo "Install Liquibase"
      - curl -L https://github.com/liquibase/liquibase/releases/download/v4.8.0/liquibase-4.8.0.tar.gz -o liquibase.tar.gz
      - tar xzf liquibase.tar.gz
      - liquibase --version
  build:
    commands:
      - echo Build started on `date`
      - liquibase --defaultsFile=liquibase.properties checks run
      - liquibase --defaultsFile=liquibase.properties validate
      - liquibase --defaultsFile=liquibase.properties tag codebuild-$CODEBUILD_BUILD_NUMBER
      - liquibase --defaultsFile=liquibase.properties status --verbose
      - liquibase --defaultsFile=liquibase.properties updateSql
      - liquibase --defaultsFile=liquibase.properties update
      - liquibase --defaultsFile=liquibase.properties history
      
  post_build:
    commands:
      - liquibase --defaultsFile=liquibase.properties --outputFile=codebuild-$CODEBUILD_BUILD_NUMBER.json snapshot --snapshotFormat=json
      - echo Build completed on `date`
artifacts:
  files:
    - codebuild-$CODEBUILD_BUILD_NUMBER.json
